# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'FireChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireChat
  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # Facebook
  pod 'FBSDKLoginKit' 
 

  target 'FireChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FireChatUITests' do
    # Pods for testing
  end

end
